### ISSUE TITLE
UVC混淆问题

### ISSUE THREAD

**Issue by sineom-1** [XXApple/AndroidLibs#81]
大佬有进行UVC的混淆么？ com.serenegiant.media.MediaMoviePlayer: can't find referenced method 'void setDataSource(android.content.res.AssetFileDescriptor)' in library class android.media.MediaExtractor  混淆一直报这个错误

**Comment by jp1017** [comment]
@IT-crackpot 你这个类是这里的: https://github.com/saki4510t/libcommon, 你确定用到这个? 这个用到上面的库, https://github.com/saki4510t/UVCCamera , 但是没用这个类, 你用到了?

**Comment by sineom-1** [comment]
没有使用这个类，但是有一个视频使用到系统的MediaPlayer ，那应该是冲突了吧

**Comment by jp1017** [comment]
不冲突啊,怎么了,不混淆正常吗?

**Comment by sineom-1** [comment]
是的，混淆后直接报上述那个错误
 try {
            mMediaPlayer.setSurface(mSw);
            mMediaPlayer.setDataSource(mVideoPath);
            mMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
            mMediaPlayer.prepare();
            mMediaPlayer.start();
            mMediaPlayer.pause();
            setAllTimeDuration();
        } catch (IOException e) {
            e.printStackTrace();
        }
这个视频类的注释掉就没问题了

**Comment by sineom-1** [comment]
大佬  加个QQ或者微信呗，我的邮箱 sineom@126.com

**Comment by jp1017** [comment]
qq:　786241016
