### ISSUE TITLE
关于热更新

### ISSUE THREAD

**Issue by bluejww** [XXApple/AndroidLibs#86]
你们好，看到现在很多项目用到了热更新或者说是热修复，美团的热更新技术，能不能把这块的项目也加紧收罗起来，为广大android开发者提供以便利。

**Comment by jp1017** [comment]
[开发框架Framework](https://github.com/XXApple/AndroidLibs/tree/master/%E5%BC%80%E5%8F%91%E6%A1%86%E6%9E%B6Framework) 这里有好多的啊,可以搜搜AppAddUpdate, 这个后面有好几个哦, 直接链接不过去了呢?, 你自己搜下
